# Generated by Django 4.2.13 on 2024-07-26 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_product_cover_company_company_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_price_10',
            new_name='product_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_price_100',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_price_1000',
        ),
    ]
